window.FLLegacySystems = (() => {
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
  const hash=text=>{let h=2166136261;for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
  const seeded=seed=>{let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296}};
  const pick=(arr,r)=>arr[Math.floor(r()*arr.length)];
  const yearOf=value=>Number(String(value||'1888').slice(0,4))||1888;
  const controlled=game=>window.FLGame?.controlledClub(game)||(game.clubs||[]).find(c=>c.id===game.controlledClubId);
  const inbox=(game,from,subject,body,id)=>{game.inbox=Array.isArray(game.inbox)?game.inbox:[];if(!game.inbox.some(x=>x.id===id))game.inbox.unshift({id,date:game.date,from,subject,body,read:false})};
  const history=(game,row)=>{game.history=Array.isArray(game.history)?game.history:[];if(!game.history.some(x=>x.id===row.id))game.history.push(row)};
  const firstNames={male:['Arthur','George','William','Thomas','Edward','Henry','James','Robert','Frederick','Charles','Daniel','Samuel','Joseph','Alfred','Michael','David','Peter','John','Oliver','Elliot','Marcus','Theo','Noah'],female:['Mary','Elizabeth','Margaret','Alice','Florence','Eleanor','Edith','Grace','Clara','Rose','Helen','Sarah','Catherine','Anna','Emily','Sophie','Maya','Olivia','Amelia','Isla']};
  const surnames=['Bennett','Mercer','Wright','Taylor','Cooper','Fletcher','Morris','Hughes','Walker','Clarke','Ward','Parker','Turner','Evans','Morgan','Reed','Price','Carter'];

  const faceDefaults={skin:'medium',hair:'brown',hairStyle:'side-part',facialHair:'moustache',eyes:'brown',faceShape:'oval',outfit:'suit',accessory:'none'};
  const palettes={
    skin:{light:'#f0c7a6',fair:'#e5b28e',medium:'#bd805e',tan:'#9a6045',deep:'#70452f',dark:'#4c2e22'},
    hair:{black:'#171311',brown:'#4a2b1d',auburn:'#743523',blond:'#c49a58',grey:'#77736f',white:'#d9d7ce'},
    eyes:{blue:'#5d84a7',green:'#5b7c55',hazel:'#806a3f',brown:'#4d3526',grey:'#707b82'}
  };
  function normaliseFace(face={},seedText='manager'){
    const r=seeded(hash(seedText));
    return {...faceDefaults,
      skin:face.skin||pick(Object.keys(palettes.skin),r),hair:face.hair||pick(Object.keys(palettes.hair),r),eyes:face.eyes||pick(Object.keys(palettes.eyes),r),
      hairStyle:face.hairStyle||pick(['side-part','short','swept','receding','wavy'],r),facialHair:face.facialHair||pick(['none','moustache','full-beard','goatee'],r),
      faceShape:face.faceShape||pick(['oval','square','round','long'],r),outfit:face.outfit||'suit',accessory:face.accessory||'none'};
  }
  function mutateFace(parent,seedText){
    const r=seeded(hash(seedText)),base=normaliseFace(parent,seedText);
    const change=(key,options,chance=.34)=>r()<chance?pick(options,r):base[key];
    return {...base,skin:change('skin',Object.keys(palettes.skin),.2),hair:change('hair',Object.keys(palettes.hair),.42),eyes:change('eyes',Object.keys(palettes.eyes),.18),hairStyle:change('hairStyle',['side-part','short','swept','receding','wavy','curly'],.55),facialHair:change('facialHair',['none','moustache','full-beard','goatee'],.7),faceShape:change('faceShape',['oval','square','round','long'],.28),accessory:'none'};
  }
  function avatarSvg(face={},age=35,label='Manager'){
    const f=normaliseFace(face,label),skin=palettes.skin[f.skin]||palettes.skin.medium,hair=palettes.hair[f.hair]||palettes.hair.brown,eye=palettes.eyes[f.eyes]||palettes.eyes.brown;
    const old=Number(age)>=55,veryOld=Number(age)>=70,shape={oval:'M58 42 Q100 18 142 42 L148 112 Q143 167 100 180 Q57 167 52 112 Z',square:'M55 42 Q100 20 145 42 L147 129 Q139 176 100 181 Q61 176 53 129 Z',round:'M52 57 Q100 20 148 57 L150 116 Q143 171 100 180 Q57 171 50 116 Z',long:'M62 34 Q100 18 138 34 L145 119 Q139 184 100 192 Q61 184 55 119 Z'}[f.faceShape]||'';
    const hairPath={
      'side-part':'M54 68 Q57 24 100 24 Q138 24 147 61 Q119 48 91 48 Q72 50 54 68 Z',short:'M56 64 Q63 27 100 25 Q137 27 144 64 Q120 48 100 47 Q78 48 56 64 Z',
      swept:'M51 70 Q58 24 100 23 Q141 24 150 63 Q129 44 91 47 Q71 52 51 70 Z',receding:'M62 56 Q72 30 91 29 L100 44 L109 29 Q130 31 139 57 Q121 49 100 51 Q79 49 62 56 Z',
      wavy:'M51 68 Q55 27 76 30 Q89 16 101 29 Q117 14 128 31 Q147 33 149 66 Q129 47 101 48 Q73 47 51 68 Z',curly:'M52 70 Q50 37 69 36 Q69 19 89 28 Q102 12 112 29 Q132 18 136 38 Q151 41 148 70 Q125 48 100 50 Q75 48 52 70 Z'
    }[f.hairStyle]||'';
    const facial=f.facialHair==='moustache'?`<path d="M77 126 Q90 116 100 126 Q110 116 123 126 Q111 139 100 132 Q89 139 77 126Z" fill="${hair}"/>`:f.facialHair==='goatee'?`<path d="M82 126 Q100 117 118 126 Q113 143 100 154 Q87 143 82 126Z" fill="${hair}" opacity=".92"/>`:f.facialHair==='full-beard'?`<path d="M62 116 Q68 165 100 179 Q132 165 138 116 Q125 137 100 144 Q75 137 62 116Z" fill="${hair}" opacity=".94"/>`:'';
    const outfit=f.outfit==='tracksuit'?'<path d="M35 240 Q38 187 70 177 L100 213 L130 177 Q162 187 165 240Z" fill="#244a63"/><path d="M100 181V240" stroke="#e7e7e0" stroke-width="4"/>':f.outfit==='coat'?'<path d="M31 240 Q38 184 70 174 L100 204 L130 174 Q163 184 169 240Z" fill="#312e2c"/><path d="M70 174L100 215L130 174" fill="#5c574f"/>':'<path d="M34 240 Q39 185 71 176 L100 212 L129 176 Q161 185 166 240Z" fill="#172738"/><path d="M72 176L100 213L128 176" fill="#ece6d8"/><path d="M95 202L100 232L105 202Z" fill="#873333"/>';
    const glasses=f.accessory==='glasses'?`<g fill="none" stroke="#322c28" stroke-width="4"><rect x="61" y="91" width="31" height="22" rx="8"/><rect x="108" y="91" width="31" height="22" rx="8"/><path d="M92 99H108"/></g>`:'';
    const wrinkles=old?`<g fill="none" stroke="#8e5d49" stroke-width="1.5" opacity="${veryOld?.6:.35}"><path d="M65 81Q79 76 90 81M110 81Q122 76 136 82M73 142Q100 151 127 142"/></g>`:'';
    const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 240"><defs><linearGradient id="bg" x1="0" x2="1"><stop stop-color="#0b273c"/><stop offset="1" stop-color="#154560"/></linearGradient></defs><rect width="200" height="240" fill="url(#bg)"/><circle cx="100" cy="65" r="72" fill="#ffffff" opacity=".035"/>${outfit}<path d="${shape}" fill="${skin}"/><path d="${hairPath}" fill="${veryOld?palettes.hair.grey:hair}"/><ellipse cx="78" cy="101" rx="8" ry="5" fill="#f6f0e7"/><ellipse cx="122" cy="101" rx="8" ry="5" fill="#f6f0e7"/><circle cx="79" cy="101" r="3.2" fill="${eye}"/><circle cx="121" cy="101" r="3.2" fill="${eye}"/><path d="M96 103 Q91 121 101 124" fill="none" stroke="#8d5c49" stroke-width="2"/><path d="M81 145 Q100 153 119 145" fill="none" stroke="#7b443b" stroke-width="3" stroke-linecap="round"/>${facial}${glasses}${wrinkles}<text x="100" y="228" text-anchor="middle" font-family="Arial" font-size="8" fill="#efe7d7" opacity=".75">${String(label).replace(/[<>&]/g,'')}</text></svg>`;
    return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
  }
  function managerPortrait(manager,year=1888){if(window.FLEraIdentity)return FLEraIdentity.portraitFor({...manager,age:Number(manager?.age)||35,identitySeed:manager?.identitySeed||manager?.appearanceSeed||hash(`${manager?.firstName||''}-${manager?.lastName||''}`),skinTone:manager?.skinTone||manager?.faceConfig?.skin ,portraitRole:'manager'},year,{role:'manager'});return manager?.portrait||'assets/player-faces/no-face.svg'};

  function globalDisasterSchedule(seed){const windows=[[1895,1928],[1932,1964],[1968,1999],[2003,2034],[2040,2090]];return windows.map((w,i)=>w[0]+(hash(`${seed}-global-disaster-window-${i}`)%(w[1]-w[0]+1)))}
  function baseState(game){
    const year=yearOf(game.date),seed=game.meta?.seed||1,manager=game.manager||{},birthYear=year-(Number(manager.age)||35),rootId=manager.personId||`dynasty-${hash(`${seed}-${manager.firstName}-${manager.lastName}`)}`;
    manager.personId=rootId;manager.faceConfig=manager.faceConfig?normaliseFace(manager.faceConfig,rootId):null;
    const earliest=Math.max(1905,Math.min(2150,year+8)),latest=Math.max(earliest,2150),scheduledYear=earliest+(hash(`${seed}-career-disaster`)%(latest-earliest+1));
    return {version:'0.22.6',family:{currentManagerPersonId:rootId,people:[{id:rootId,firstName:manager.firstName||'Arthur',lastName:manager.lastName||'Manager',gender:manager.gender||'Male',birthYear,nationality:manager.nationality||'England',birthplace:manager.birthplace||'Unknown',parentIds:[],childIds:[],generation:1,relation:'Founder',footballPath:'Manager',managerAbility:54,reputation:manager.reputation||'Unknown Local Coach',faceConfig:manager.faceConfig||normaliseFace({},rootId),active:true}],links:[],generatedThrough:year,successionHistory:[],playerDynasties:[],placedPeople:[]},disasters:{scheduledYear,occurred:false,event:null,anniversariesNotified:[]},tactics:{innovation:0,familiarity:{},firsts:[],lastContext:null},continuity:{targetYear:2150,validatedThrough:year,lastAnnualYear:year,futureMarketCycles:[]},globalDisasters:{events:[],lastYear:null,scheduledYears:globalDisasterSchedule(seed)}};
  }
  function ensure(game){
    game.legacySystems=game.legacySystems&&typeof game.legacySystems==='object'?game.legacySystems:baseState(game);
    const s=game.legacySystems;s.version='0.22.6';s.family=s.family||baseState(game).family;s.family.people=Array.isArray(s.family.people)?s.family.people:[];s.family.links=Array.isArray(s.family.links)?s.family.links:[];s.family.successionHistory=Array.isArray(s.family.successionHistory)?s.family.successionHistory:[];s.family.playerDynasties=Array.isArray(s.family.playerDynasties)?s.family.playerDynasties:[];s.family.placedPeople=Array.isArray(s.family.placedPeople)?s.family.placedPeople:[];
    s.disasters=s.disasters||baseState(game).disasters;s.disasters.anniversariesNotified=Array.isArray(s.disasters.anniversariesNotified)?s.disasters.anniversariesNotified:[];if(!Number.isFinite(Number(s.disasters.scheduledYear))&&!s.disasters.occurred){const y=yearOf(game.date);s.disasters.scheduledYear=Math.min(2150,y+8+(hash(`${game.meta?.seed||1}-${game.controlledClubId}-career-disaster`)%85))}delete s.disasters.disabled;
    s.globalDisasters=s.globalDisasters||{events:[],lastYear:null,scheduledYears:globalDisasterSchedule(game.meta?.seed||1)};s.globalDisasters.events=Array.isArray(s.globalDisasters.events)?s.globalDisasters.events:[];s.globalDisasters.scheduledYears=Array.isArray(s.globalDisasters.scheduledYears)&&s.globalDisasters.scheduledYears.length?s.globalDisasters.scheduledYears:globalDisasterSchedule(game.meta?.seed||1);
    s.tactics=s.tactics||{innovation:0,familiarity:{},firsts:[],lastContext:null};s.tactics.familiarity=s.tactics.familiarity||{};s.tactics.firsts=Array.isArray(s.tactics.firsts)?s.tactics.firsts:[];
    s.continuity=s.continuity||{targetYear:2150,validatedThrough:yearOf(game.date),lastAnnualYear:yearOf(game.date),futureMarketCycles:[]};s.continuity.targetYear=Math.max(2150,Number(s.continuity.targetYear)||2150);s.continuity.futureMarketCycles=Array.isArray(s.continuity.futureMarketCycles)?s.continuity.futureMarketCycles:[];
    if(!s.family.people.length){const fresh=baseState(game);s.family=fresh.family}
    const current=s.family.people.find(p=>p.id===s.family.currentManagerPersonId)||s.family.people[0];if(current){game.manager.personId=current.id;if(!game.manager.faceConfig&&current.faceConfig)game.manager.faceConfig=current.faceConfig;current.active=true}
    if(window.FLPeople){FLPeople.ensure(game);FLPeople.syncLegacyFamily(game);}
    game.version='0.22.6';return s;
  }
  function relationLabel(generation){return generation===1?'Founder':generation===2?'Child':generation===3?'Grandchild':generation===4?'Great-grandchild':`${generation-2}× great-grandchild`}
  function addPerson(game,parent,birthYear,index){
    const s=ensure(game),r=seeded(hash(`${game.meta?.seed||1}-${parent.id}-${birthYear}-${index}`)),gender=r()<.46?'Female':'Male',first=pick(firstNames[gender.toLowerCase()],r),last=parent.lastName||pick(surnames,r),id=`family-${hash(`${parent.id}-${first}-${birthYear}-${index}`)}`;
    if(s.family.people.some(p=>p.id===id))return null;
    const pathRoll=r(),footballPath=gender==='Male'&&pathRoll<.18?'Player':pathRoll<.39?'Manager':pathRoll<.56?'Coach':pathRoll<.66?'Scout':'Outside football';
    const person={id,firstName:first,lastName:last,gender,birthYear,nationality:parent.nationality||game.manager.nationality||'England',birthplace:parent.birthplace||game.manager.birthplace||'Unknown',parentIds:[parent.id],childIds:[],generation:(parent.generation||1)+1,relation:relationLabel((parent.generation||1)+1),footballPath,managerAbility:35+Math.floor(r()*55),playingTalent:35+Math.floor(r()*61),professionalism:25+Math.floor(r()*75),reputation:'Unknown',faceConfig:mutateFace(parent.faceConfig,`${id}-face`),active:false};
    s.family.people.push(person);parent.childIds=Array.isArray(parent.childIds)?parent.childIds:[];parent.childIds.push(id);s.family.links.push({parentId:parent.id,childId:id});
    if(window.FLPeople){const canonical=FLPeople.create(game,{id,firstName, lastName:last,gender,birthYear,nationality:person.nationality,birthplace:person.birthplace,parentIds:[parent.personId||parent.id],footballRoles:[footballPath.toLowerCase().replace('outside football','family')],currentRole:footballPath.toLowerCase(),reputation:person.reputation});person.personId=canonical.id;person.appearanceSeed=canonical.appearanceSeed;person.appearanceIndex=canonical.appearanceIndex;}
    return person;
  }
  function bootstrapFamily(game){
    const s=ensure(game),root=s.family.people[0],currentYear=yearOf(game.date);if(root.familyBootstrapped)return;
    // Personal-life events are the sole source of the user's spouse and direct children.
    // Legacy generation continues from those children into later generations.
    if(window.FLPersonalLife){root.familyBootstrapped=true;s.family.generatedThrough=currentYear;return;}
    const r=seeded(hash(`${game.meta?.seed||1}-${root.id}-bootstrap`)),count=1+Math.floor(r()*3);
    for(let i=0;i<count;i++){const born=root.birthYear+23+i*4+Math.floor(r()*6);if(born<=currentYear-2)addPerson(game,root,born,i)}
    [...s.family.people].filter(p=>p.generation===2&&currentYear-p.birthYear>=24).forEach((parent,i)=>{if(r()<.58)addPerson(game,parent,parent.birthYear+24+Math.floor(r()*9),i)});
    const descendants=s.family.people.filter(p=>p.id!==root.id);if(descendants.length&&!descendants.some(p=>p.footballPath==='Manager')){const heir=descendants.sort((a,b)=>a.generation-b.generation||b.managerAbility-a.managerAbility)[0];heir.footballPath='Manager';heir.managerAbility=Math.max(58,heir.managerAbility)}
    root.familyBootstrapped=true;s.family.generatedThrough=currentYear;
  }
  function personName(p){return `${p.firstName} ${p.lastName}`}
  function playerTemplate(game,person,club){
    const r=seeded(hash(`${game.meta?.seed||1}-${person.id}-player`)),position=pick(['GK','FB','HB','IF','CF','W'],r),ability=clamp(34+Math.floor(r()*28)+(person.playingTalent>=88?8:0),32,78),ceiling=clamp(Math.max(ability,person.playingTalent+Math.floor((r()-.5)*10)),ability,98);
    return {id:`dynasty-player-${person.id}`,personId:person.personId||person.id,name:personName(person),gender:'male',clubId:club?.id||null,position,age:clamp(yearOf(game.date)-person.birthYear,15,18),condition:95,form:'—',ability,potential:Math.round((ability+ceiling)/2),ceiling,talentCap:ceiling,nationality:person.nationality==='England'?'English':person.nationality,developmentCurve:person.professionalism>75?'steady':r()<.25?'late':'volatile',personalityProfile:{professionalism:person.professionalism,ambition:35+Math.floor(r()*65),loyalty:35+Math.floor(r()*65),leadership:25+Math.floor(r()*70),bigMatches:25+Math.floor(r()*70),consistency:35+Math.floor(r()*60),injuryProneness:10+Math.floor(r()*75),temperament:25+Math.floor(r()*70),teamwork:35+Math.floor(r()*60),determination:person.professionalism,adaptability:30+Math.floor(r()*65),resilience:30+Math.floor(r()*65),confidenceStability:30+Math.floor(r()*65)},personalityLabel:'Football family prospect',wage:0,appearances:0,starts:0,subApps:0,minutes:0,goals:0,assists:0,yellowCards:0,redCards:0,cleanSheets:0,conceded:0,playerOfMatch:0,averageRating:'—',honours:[],seasonHistory:[],matchHistory:[],familyPersonId:person.personId||person.id,parentPersonIds:person.parentIds,identitySeed:person.appearanceSeed,appearanceIndex:person.appearanceIndex,identityNameLocked:true,face:window.FLEraIdentity?FLEraIdentity.portraitFor({...person,gender:'male',age:17},yearOf(game.date)):'assets/real-portraits/faces/rp-001-1.webp'};
  }
  function placeFamilyMember(game,person){
    const s=ensure(game),year=yearOf(game.date),age=year-person.birthYear;if(s.family.placedPeople.includes(person.id))return;const directPersonalChild=Boolean(window.FLPersonalLife&&game.personalLife?.children?.some(c=>(c.personId||c.id)===(person.personId||person.id)));if(directPersonalChild)return;
    if(person.footballPath==='Player'&&age>=15&&age<=18){const c=controlled(game),p=playerTemplate(game,person,c);p.generatedYear=year;p.birthYear=person.birthYear;if(window.FLEraIdentity)FLEraIdentity.applyPlayer(game,p,year);if(window.FLEconomy)p.wage=FLEconomy.recommendedWage(game,p,c,'Prospect');c.players.push(p);window.FLLivingWorld?.ensurePlayer(game,p,c);s.family.placedPeople.push(person.id);person.clubId=c.id;person.playerId=p.id;person.reputation='Academy prospect';inbox(game,'Youth Development Officer',`${personName(person)} joins the academy`,`${personName(person)}, a ${person.relation.toLowerCase()} of the managerial family, has entered the youth system. The surname creates attention, but the staff will judge the player on ability rather than family reputation.`,`family-player-${person.id}`)}
    if(['Manager','Coach','Scout'].includes(person.footballPath)&&age>=28){s.family.placedPeople.push(person.id);person.reputation=person.managerAbility>=78?'Highly regarded':person.managerAbility>=58?'Promising':'Unproven';if(person.footballPath!=='Manager'){const c=controlled(game);c.staff=c.staff||[];if(!c.staff.some(x=>x.familyPersonId===person.id))c.staff.push({id:`family-staff-${person.id}`,name:personName(person),role:person.footballPath,appointed:game.date,familyPersonId:person.id,quality:person.managerAbility})}}
  }
  function generateFamilyThrough(game,targetYear){
    const s=ensure(game);bootstrapFamily(game);let from=Math.max(1888,Number(s.family.generatedThrough||yearOf(game.date)))+1;
    for(let year=from;year<=targetYear;year++){
      const eligible=[...s.family.people].filter(p=>p.id!==s.family.currentManagerPersonId&&year-p.birthYear>=24&&year-p.birthYear<=44&&(p.childIds||[]).length<3);
      eligible.forEach((parent,i)=>{const r=seeded(hash(`${game.meta?.seed||1}-${parent.id}-${year}-birth`)),chance=parent.generation<=3?.055:.035;if(r()<chance)addPerson(game,parent,year,i)});
      s.family.people.forEach(person=>{if(year-person.birthYear>=15)placeFamilyMember(game,person)});
      s.family.generatedThrough=year;
    }
  }
  function notablePlayer(game){
    const all=(game.clubs||[]).flatMap(c=>(c.players||[]).map(p=>({p,c}))).filter(x=>!x.p.legacyChildGenerated&&(Number(x.p.age)||0)>=36&&((Number(x.p.careerTotals?.appearances)||0)>=120||(Number(x.p.ability)||0)>=82));
    return all.sort((a,b)=>(Number(b.p.careerTotals?.appearances)||0)-(Number(a.p.careerTotals?.appearances)||0))[0]||null;
  }
  function generatePlayerDynasty(game,year){
    const s=ensure(game),candidate=notablePlayer(game);if(!candidate)return null;const r=seeded(hash(`${game.meta?.seed||1}-${candidate.p.id}-${year}-legacy-child`));if(r()>.22)return null;
    const first=pick(firstNames.male,r),last=candidate.p.name.split(' ').slice(-1)[0],id=`legacy-reg-${hash(`${candidate.p.id}-${year}`)}`,ability=38+Math.floor(r()*22),ceiling=clamp(58+Math.floor(r()*39)+((candidate.p.ability||50)>=88?3:0),ability,99),age=15+Math.floor(r()*3);
    const child={id,name:`${first} ${last}`,clubId:candidate.c.id,position:pick(['GK','FB','HB','IF','CF','W'],r),age,condition:96,form:'—',ability,potential:Math.round((ability+ceiling)/2),ceiling,talentCap:ceiling,nationality:candidate.p.nationality||'English',developmentCurve:r()<.2?'early':r()<.45?'late':'steady',personalityProfile:{professionalism:30+Math.floor(r()*70),ambition:30+Math.floor(r()*70),loyalty:30+Math.floor(r()*70),leadership:20+Math.floor(r()*75),bigMatches:25+Math.floor(r()*70),consistency:30+Math.floor(r()*65),injuryProneness:8+Math.floor(r()*80),temperament:25+Math.floor(r()*70),teamwork:30+Math.floor(r()*65),determination:30+Math.floor(r()*70),adaptability:25+Math.floor(r()*70)},personalityLabel:'Second-generation footballer',wage:0,appearances:0,starts:0,subApps:0,minutes:0,goals:0,assists:0,yellowCards:0,redCards:0,cleanSheets:0,conceded:0,playerOfMatch:0,averageRating:'—',honours:[],seasonHistory:[],matchHistory:[],parentPlayerId:candidate.p.id,familyGeneration:Number(candidate.p.familyGeneration||1)+1};
    child.generatedYear=year;child.birthYear=year-age;if(window.FLEraIdentity)FLEraIdentity.applyPlayer(game,child,year);if(window.FLEconomy)child.wage=FLEconomy.recommendedWage(game,child,candidate.c,'Prospect');candidate.p.legacyChildGenerated=true;candidate.c.players.push(child);window.FLLivingWorld?.ensurePlayer(game,child,candidate.c);s.family.playerDynasties.push({parentPlayerId:candidate.p.id,parentName:candidate.p.name,childPlayerId:child.id,childName:child.name,year,clubId:candidate.c.id});inbox(game,'Football Correspondent',`${child.name} follows a famous surname`,`${child.name}, child of ${candidate.p.name}, has entered senior football. The family connection brings expectation, but the player’s own career will determine the legacy.`,`player-dynasty-${child.id}`);return child;
  }
  function eligibleSuccessors(game){
    const s=ensure(game),year=yearOf(game.date),preferred=game.personalLife?.relationshipJourney?.preferredSuccessorPersonId||null;return s.family.people.filter(p=>p.id!==s.family.currentManagerPersonId&&p.footballPath==='Manager'&&year-p.birthYear>=28&&s.family.placedPeople.includes(p.id)).sort((a,b)=>{const ap=a.id===preferred?1:0,bp=b.id===preferred?1:0;return bp-ap||b.managerAbility-a.managerAbility});
  }
  function queueSuccession(game,request={}){
    const s=ensure(game),year=yearOf(game.date),current=s.family.people.find(p=>p.id===s.family.currentManagerPersonId),age=current?year-current.birthYear:Number(game.manager.age||35),force=Boolean(request.force);if((!force&&age<68)||(!force&&s.family.lastSuccessionPromptYear===year)||window.FLLivingWorld?.pending(game,'succession')?.length)return null;
    const successors=eligibleSuccessors(game).slice(0,3),options=[...successors.map(p=>({id:`family:${p.id}`,label:`Hand the role to ${personName(p)}`,effect:`Continue as your ${p.relation.toLowerCase()}; managerial ability ${p.managerAbility>=78?'highly regarded':p.managerAbility>=58?'promising':'unproven'}.`})),{id:'assistant',label:'Promote the assistant manager',effect:'Continue the save through an experienced club servant.'},{id:'new-manager',label:'Begin with a completely new manager',effect:'Create a fresh manager while retaining the full world, club and previous-career history.'},...(!force?[{id:'continue',label:'Continue for one more season',effect:'Delay succession, with age and health increasingly part of the story.'}]:[])];
    s.family.lastSuccessionPromptYear=year;return window.FLLivingWorld?.queueDecision(game,{id:`succession-${year}-${current?.id||'manager'}-${force?'retirement':'age'}`,type:'succession',targetTab:'manager',title:request.retirement?'Retirement and succession':'The future of the managerial legacy',detail:request.retirement?`${personName(current)} has announced retirement. Choose who will continue the save.`:`At ${age}, questions are being asked about succession. A family appointment may strengthen the dynasty, but supporters will reject obvious nepotism if the candidate has not earned the role.`,from:'Club Chairman',blocking:true,payload:{currentPersonId:current?.id,year,retirement:Boolean(request.retirement)},options});
  }
  function appointPerson(game,person,source){
    const s=ensure(game),year=yearOf(game.date),old=s.family.people.find(p=>p.id===s.family.currentManagerPersonId);if(old){old.active=false;old.retiredYear=year}
    person.active=true;person.footballPath='Manager';person.reputation=person.managerAbility>=80?'Highly Regarded Manager':person.managerAbility>=60?'Promising Manager':'Unproven Manager';s.family.currentManagerPersonId=person.id;s.family.successionHistory.push({year,fromId:old?.id,toId:person.id,fromName:old?personName(old):'',toName:personName(person),source});
    game.managerArchive=Array.isArray(game.managerArchive)?game.managerArchive:[];if(old)game.managerArchive.push({id:old.id,name:personName(old),from:game.manager.appointedDate||'1888-08-15',to:game.date,club:controlled(game)?.name||'',familyGeneration:old.generation});
    game.manager={...game.manager,personId:person.id,firstName:person.firstName,lastName:person.lastName,age:year-person.birthYear,nationality:person.nationality,birthplace:person.birthplace,portrait:window.FLEraIdentity?FLEraIdentity.portraitFor({...person,gender:person.gender,age:year-person.birthYear,identitySeed:person.appearanceSeed,appearanceIndex:person.appearanceIndex,portraitRole:'manager'},year,{role:'manager'}):'assets/player-faces/no-face.svg',faceConfig:person.faceConfig,appointedDate:game.date,reputation:person.reputation,occupation:source==='Family succession'?'Football family successor':'Assistant manager'};
    if(window.FLPeople){const canonical=FLPeople.create(game,{id:person.personId||person.id,firstName:person.firstName,lastName:person.lastName,gender:person.gender,birthYear:person.birthYear,nationality:person.nationality,birthplace:person.birthplace,parentIds:person.parentIds||[],footballRoles:['manager'],currentRole:'manager',reputation:person.reputation,appearanceSeed:person.appearanceSeed,appearanceIndex:person.appearanceIndex,roleLinks:{manager:true}});person.personId=canonical.id;game.manager.personId=canonical.id;game.people.managerPersonId=canonical.id;}
    if(window.FLPersonalLife)FLPersonalLife.switchHousehold(game,person.personId||person.id);
    game.managerCareer.timeline.push({date:game.date,title:`${personName(person)} becomes manager`,text:`The ${person.relation.toLowerCase()} continues the managerial legacy at ${controlled(game)?.name}.`});history(game,{id:`manager-succession-${person.id}-${year}`,date:game.date,type:'manager',title:'Managerial succession',text:`${personName(person)} succeeded ${old?personName(old):'the previous manager'} at ${controlled(game)?.name}.`});if(window.FLManagerLegacyCareer)FLManagerLegacyCareer.onSuccession(game,old,person,source);
  }
  function resolveSuccession(game,decision,option){
    const s=ensure(game),year=yearOf(game.date);if(option.id==='continue'){return {ok:true,message:'You remain in charge for another season. The succession question will return if the career continues.'}}
    let person,source='Assistant succession';if(option.id.startsWith('family:')){person=s.family.people.find(p=>p.id===option.id.split(':')[1]);source='Family succession';}
    if(!person){const fresh=option.id==='new-manager',r=seeded(hash(`${game.meta?.seed||1}-${year}-${fresh?'new':'assistant'}-successor`)),id=`${fresh?'new':'assistant'}-successor-${year}-${Math.floor(r()*9999)}`,last=pick(surnames,r);person={id,firstName:pick(firstNames.male,r),lastName:last,gender:'Male',birthYear:year-(fresh?28+Math.floor(r()*22):32+Math.floor(r()*24)),nationality:game.manager.nationality||'England',birthplace:fresh?'England':game.manager.birthplace||'Unknown',parentIds:[],childIds:[],generation:1,relation:fresh?'New manager':'Non-family successor',footballPath:'Manager',managerAbility:fresh?42+Math.floor(r()*34):55+Math.floor(r()*28),professionalism:45+Math.floor(r()*50),reputation:fresh?'Unproven Manager':'Experienced Assistant',faceConfig:normaliseFace({},id),active:false};s.family.people.push(person);source=fresh?'New manager succession':'Assistant succession';}
    const weakFamily=person.parentIds?.length&&person.managerAbility<50;if(weakFamily){game.boardConfidence=clamp((game.boardConfidence||50)-7,0,100);game.managerCareer.relationships.supporters=clamp((game.managerCareer.relationships.supporters||50)-8,0,100)}else{game.boardConfidence=clamp((game.boardConfidence||50)+2,0,100)}
    appointPerson(game,person,source);return {ok:true,message:`${personName(person)} has been appointed. ${weakFamily?'The appointment is immediately criticised as nepotistic.':'The succession is accepted as a credible continuation of the club’s history.'}`};
  }

  function disasterTemplate(year,r){
    const early=year<1930,mid=year<1975;
    const list=early?[{id:'stand-collapse',title:'Serious stadium structural failure',setting:'A section of the ground fails during a crowded fixture.'},{id:'rail-accident',title:'Team railway disaster',setting:'A club train is involved in a major accident while travelling to a fixture.'}]:mid?[{id:'stadium-fire',title:'Major stadium fire',setting:'A fire breaks out at the ground and the emergency response continues into the evening.'},{id:'team-air',title:'Team air disaster',setting:'An aircraft carrying members of the club fails to arrive safely.'},{id:'crowd-crush',title:'Fatal crowd disaster',setting:'A dangerous crowd movement causes loss of life and serious injury.'}]:[{id:'crowd-crush',title:'Fatal crowd disaster',setting:'A dangerous crowd movement causes loss of life and serious injury.'},{id:'team-transport',title:'Team transport disaster',setting:'Club personnel are involved in a major travel accident.'},{id:'stadium-failure',title:'Major stadium emergency',setting:'A serious failure at the ground leads to loss of life and a full safety investigation.'}];return pick(list,r)
  }
  function triggerDisaster(game){
    const s=ensure(game),d=s.disasters;if(d.occurred)return null;const year=yearOf(game.date);if(year!==d.scheduledYear)return null;
    const c=controlled(game),r=seeded(hash(`${game.meta?.seed||1}-${year}-major-disaster`)),template=disasterTemplate(year,r),available=(c.players||[]).filter(p=>p.status!=='deceased'&&p.status!=='retired'),lossCount=Math.min(available.length,1+Math.floor(r()*3)),victims=[];
    for(let i=0;i<lossCount;i++){const index=Math.floor(r()*available.length),p=available.splice(index,1)[0];if(!p)continue;p.status='deceased';p.available=false;p.careerStory=Array.isArray(p.careerStory)?p.careerStory:[];p.careerStory.push({date:game.date,title:'Remembered by the club',text:'Died in the club disaster. The game records the player with dignity and without graphic detail.'});victims.push({id:p.id,name:p.name,role:'Player'})}
    const survivor=available[Math.floor(r()*available.length)];if(survivor){survivor.permanentInjury={name:'Life-changing injuries sustained in the club disaster',careerEnding:r()<.65};if(survivor.permanentInjury.careerEnding){survivor.status='retired';survivor.available=false}}
    d.occurred=true;d.event={id:`disaster-${year}`,year,date:game.date,type:template.id,title:template.title,setting:template.setting,clubId:c.id,clubName:c.name,victims,survivor:survivor?{id:survivor.id,name:survivor.name,careerEnding:survivor.permanentInjury.careerEnding}:null,recovery:null};
    c.heritage=c.heritage||{traditions:[],famousMatches:[],culture:{}};c.heritage.traditions=Array.isArray(c.heritage.traditions)?c.heritage.traditions:[];c.heritage.traditions.push({id:`memorial-${year}`,from:year,title:'Annual remembrance',detail:`The club remembers those lost in the ${year} disaster.`});c.legacyEvents=Array.isArray(c.legacyEvents)?c.legacyEvents:[];c.legacyEvents.push({date:game.date,title:template.title,type:'memorial',detail:`${victims.length} members of the playing staff were lost. A permanent memorial was established.`});
    (game.fixtures||[]).filter(f=>!f.played&&(f.home===c.id||f.away===c.id)&&f.date>=game.date&&f.date<=`${year}-12-31`).slice(0,3).forEach(f=>{const dt=new Date(`${f.date}T12:00:00Z`);dt.setUTCDate(dt.getUTCDate()+21);f.originalDate=f.date;f.date=dt.toISOString().slice(0,10);f.postponedReason='Club disaster and period of mourning'});
    history(game,{id:d.event.id,date:game.date,type:'memorial',title:template.title,text:`${c.name} enters a period of mourning. ${victims.map(v=>v.name).join(', ')} ${victims.length===1?'is':'are'} remembered permanently by the club.`});
    return window.FLLivingWorld?.queueDecision(game,{id:`disaster-response-${year}`,type:'major-disaster',targetTab:'club',title:template.title,detail:`${template.setting} The club has confirmed fatalities and serious injuries. Football has been suspended while families are supported and an independent inquiry begins.`,from:'Club Chairman',blocking:true,payload:{eventId:d.event.id},options:[{id:'community-first',label:'Put families and community first',effect:'Fund full support, suspend football and accept a slower sporting recovery.'},{id:'inquiry-led',label:'Follow the inquiry and plan a phased return',effect:'Balance long-term support with a careful return to football.'},{id:'rapid-return',label:'Push for an early sporting return',effect:'Protect short-term finances, but risk appearing insensitive.'}]});
  }
  function resolveDisaster(game,decision,option){
    const s=ensure(game),event=s.disasters.event,c=controlled(game);if(!event)return {ok:false,message:'The disaster record could not be found.'};let message='';
    if(option.id==='community-first'){game.finances.balance=Math.max(0,(game.finances.balance||0)-260);game.boardConfidence=clamp((game.boardConfidence||50)+6,0,100);game.managerCareer.relationships.supporters=clamp((game.managerCareer.relationships.supporters||50)+15,0,100);game.managerCareer.relationships.players=clamp((game.managerCareer.relationships.players||50)+12,0,100);event.recovery='Community-first recovery';message='The club funds long-term family support, postpones football and establishes a permanent memorial foundation.'}
    else if(option.id==='inquiry-led'){game.finances.balance=Math.max(0,(game.finances.balance||0)-145);game.boardConfidence=clamp((game.boardConfidence||50)+3,0,100);game.managerCareer.relationships.supporters=clamp((game.managerCareer.relationships.supporters||50)+7,0,100);event.recovery='Inquiry-led phased return';message='The club cooperates fully with the inquiry and returns only after safety and family-support measures are agreed.'}
    else{game.finances.balance=(game.finances.balance||0)+40;game.boardConfidence=clamp((game.boardConfidence||50)-4,0,100);game.managerCareer.relationships.supporters=clamp((game.managerCareer.relationships.supporters||50)-14,0,100);game.managerCareer.relationships.players=clamp((game.managerCareer.relationships.players||50)-8,0,100);event.recovery='Controversial early return';message='The club returns earlier than many supporters believe appropriate. The decision remains part of the manager’s permanent record.'}
    game.managerCareer.timeline.push({date:game.date,title:'Led the club through tragedy',text:message});inbox(game,'Club Memorial Committee','Recovery plan confirmed',message,`disaster-recovery-${event.year}`);return {ok:true,message};
  }
  function disasterAnniversary(game){
    const s=ensure(game),event=s.disasters.event;if(!event)return;const year=yearOf(game.date),years=year-event.year;if(years<1||!(years===1||years%10===0)||s.disasters.anniversariesNotified.includes(year))return;s.disasters.anniversariesNotified.push(year);inbox(game,'Club Memorial Committee',`${years}${years===1?'st':years===2?'nd':years===3?'rd':'th'} anniversary of the club disaster`,`${controlled(game)?.name} will hold a quiet remembrance for ${event.victims.map(v=>v.name).join(', ')}. The memorial remains part of the club’s history.`,`disaster-anniversary-${year}`)
  }

  function triggerGlobalDisaster(game,year){
    const s=ensure(game),global=s.globalDisasters;if(year<1895||global.events.some(e=>e.year===year)||global.events.length>=5||!global.scheduledYears.includes(year))return null;
    if(global.lastYear&&year-global.lastYear<10)return null;
    const r=seeded(hash(`${game.meta?.seed||1}-${year}-global-disaster`));
    const candidates=(game.clubs||[]).filter(c=>c.leagueActive!==false&&c.id!==game.controlledClubId&&c.id!==game.meta?.preselectedClubId);if(!candidates.length)return null;
    const c=candidates[Math.floor(r()*candidates.length)],template=disasterTemplate(year,r),players=Array.isArray(c.players)?c.players.filter(p=>p.status!=='deceased'&&p.status!=='retired'):[],victims=[];
    if(players.length>=11){const lossCount=Math.min(players.length,1+Math.floor(r()*2));for(let i=0;i<lossCount;i++){const p=players.splice(Math.floor(r()*players.length),1)[0];if(!p)continue;p.status='deceased';p.available=false;victims.push({id:p.id,name:p.name,role:'Player'})}}
    const event={id:`global-disaster-${c.id}-${year}`,year,date:`${year}-07-01`,type:template.id,title:template.title,setting:template.setting,clubId:c.id,clubName:c.name,victims};global.events.push(event);global.lastYear=year;
    c.legacyEvents=Array.isArray(c.legacyEvents)?c.legacyEvents:[];c.legacyEvents.push({date:event.date,title:event.title,type:'memorial',detail:`A major tragedy becomes a permanent part of ${c.name}'s history.`});
    history(game,{id:event.id,date:event.date,type:'world-disaster',title:`${c.name}: ${event.title}`,text:`${template.setting} ${c.name} enters a period of mourning and remembrance.`});
    game.news=Array.isArray(game.news)?game.news:[];game.news.unshift({id:event.id,date:event.date,headline:`Tragedy at ${c.name}`,body:`${template.setting} The club and its community enter a period of mourning.`,category:'history'});return event;
  }

  function eraProfile(year){
    if(year<1925)return {id:'foundations',label:'Foundational football knowledge',pressing:.45,buildUp:.58,freedom:.72,coordination:.55,terms:['Dribbling game','Combination play','Half-back cover']};
    if(year<1955)return {id:'organised',label:'Organised positional football',pressing:.58,buildUp:.7,freedom:.78,coordination:.68,terms:['Third-back organisation','Inside-forward rotations','Counter-attack']};
    if(year<1975)return {id:'systems',label:'System-led football',pressing:.74,buildUp:.82,freedom:.86,coordination:.82,terms:['Sweeper cover','Collective pressing','Fluid front line']};
    if(year<1995)return {id:'modernising',label:'Modern tactical coaching',pressing:.88,buildUp:.91,freedom:.93,coordination:.92,terms:['Compact block','High line','Overlapping full-back']};
    if(year<2020)return {id:'analysis',label:'Analysis-led football',pressing:.97,buildUp:.98,freedom:1,coordination:1,terms:['Counter-press','False nine','Positional rotations']};
    return {id:'advanced',label:'Advanced tactical era',pressing:1,buildUp:1,freedom:1.03,coordination:1.03,terms:['Rest defence','Pressing traps','Inverted rotations']};
  }
  function shapeComplexity(positions=[]){
    if(!positions.length)return .2;const xs=positions.map(p=>Number(p.x||p.width||50)),ys=positions.map(p=>Number(p.y||p.depth||50)),extreme=positions.filter(p=>(Number(p.x||p.width||50)<12||Number(p.x||p.width||50)>88||Number(p.y||p.depth||50)>84)).length/positions.length,asym=Math.abs(xs.filter(x=>x<50).length-xs.filter(x=>x>50).length)/positions.length,vertical=(Math.max(...ys)-Math.min(...ys))/100;return clamp(extreme*.35+asym*.3+vertical*.35,0,1)
  }
  function tacticalSignature(tactics={},positions=[]){return `${Math.round((tactics.pressing||50)/10)}-${Math.round((tactics.defensiveLine||50)/10)}-${Math.round((tactics.buildUp||50)/10)}-${Math.round(shapeComplexity(positions)*10)}`}
  function tacticalContext(game,tactics={},positions=[]){
    const s=ensure(game),year=yearOf(game.date),era=eraProfile(year),complexity=shapeComplexity(positions),signature=tacticalSignature(tactics,positions),familiarity=Number(s.tactics.familiarity[signature]||0),innovation=Number(s.tactics.innovation||0),pressDemand=(Number(tactics.pressing||50)/100),buildDemand=(Number(tactics.buildUp||50)/100),coordDemand=(Number(tactics.defensiveLine||50)/100)*pressDemand;
    const knowledgeGap=Math.max(0,pressDemand-era.pressing)*.45+Math.max(0,buildDemand-era.buildUp)*.28+Math.max(0,coordDemand-era.coordination)*.35+Math.max(0,complexity-era.freedom)*.22;const execution=clamp(1-knowledgeGap+Math.min(.08,familiarity/240)+Math.min(.05,innovation/500),.76,1.06),warnings=[];
    if(pressDemand>era.pressing+.18)warnings.push('Coordinated pressing is ahead of the era’s normal coaching knowledge.');if(buildDemand>era.buildUp+.2)warnings.push('The build-up requires unfamiliar positional discipline.');if(complexity>era.freedom+.2)warnings.push('The freely drawn shape is unusually complex for contemporary players.');if(!warnings.length)warnings.push('The squad understands this tactical idea within the knowledge of the era.');
    const context={year,eraId:era.id,eraLabel:era.label,execution,complexity,familiarity,innovation,signature,warnings,availableLanguage:era.terms,freePositioning:true,modifiers:{pressing:clamp(era.pressing+familiarity/180,0.4,1.08),buildUp:clamp(era.buildUp+familiarity/220,.5,1.06),coordination:clamp(era.coordination+familiarity/220,.5,1.06)}};s.tactics.lastContext=context;return context
  }
  function recordTacticalUse(game,tactics,positions,result='draw'){
    const s=ensure(game),context=tacticalContext(game,tactics,positions),gain=result==='win'?2.2:result==='draw'?1.2:.7;s.tactics.familiarity[context.signature]=clamp((s.tactics.familiarity[context.signature]||0)+gain,0,100);if(context.execution<.93&&result==='win'){s.tactics.innovation=clamp((s.tactics.innovation||0)+1.3,0,100);if(!s.tactics.firsts.some(x=>x.signature===context.signature)){s.tactics.firsts.push({date:game.date,signature:context.signature,label:`Pioneered a demanding ${context.eraLabel.toLowerCase()} system`,execution:context.execution});history(game,{id:`tactical-first-${context.signature}-${game.date}`,date:game.date,type:'manager',title:'Tactical innovation',text:`${game.manager.lastName} won with a system considered ahead of contemporary coaching knowledge.`})}}return context
  }
  function generateFutureMarket(game,year){
    const s=ensure(game);if(year<2100||s.continuity.futureMarketCycles.some(x=>year>=x.from&&year<=x.to))return;const r=seeded(hash(`${game.meta?.seed||1}-${Math.floor(year/8)}-future-market`));if(r()>.22)return;const leagues=['saudi','china','usa','brazil','japan'],leagueId=pick(leagues,r),cycle={id:`future-market-${leagueId}-${year}`,leagueId,name:`New global investment cycle in ${leagueId.toUpperCase()}`,from:year,to:year+4+Math.floor(r()*6),bids:[2,6],ageMin:27,qualityMin:80,wageMultiplier:2.8+r()*2.2,primeChance:.08+r()*.12};s.continuity.futureMarketCycles.push(cycle);if(game.livingWorld?.globalMarkets)game.livingWorld.globalMarkets.history.push({year,type:'future-cycle',name:cycle.name,detail:`A wealthy ownership cycle begins and targets selected established stars rather than the entire elite market.`});inbox(game,'World Football Desk','A new wealthy league cycle emerges',`${cycle.name} is expected to make selective high-wage offers for established stars over the next several seasons.`,`future-market-${year}`)
  }
  function activeFutureMarkets(game,year=yearOf(game.date)){return ensure(game).continuity.futureMarketCycles.filter(x=>year>=x.from&&year<=x.to)}

  function processDate(game,previousDate,currentDate){ensure(game);return {blocking:window.FLLivingWorld?.nextBlocking(game)||null}}
  function annualUpdate(game,year){const s=ensure(game);const globalDisaster=triggerGlobalDisaster(game,year);if(!game.meta?.headless){generateFamilyThrough(game,year);generatePlayerDynasty(game,year);const current=s.family.people.find(p=>p.id===s.family.currentManagerPersonId);if(current)game.manager.age=Math.max(18,year-current.birthYear);queueSuccession(game);generateFutureMarket(game,year);triggerDisaster(game);disasterAnniversary(game)}s.continuity.validatedThrough=Math.max(Number(s.continuity.validatedThrough)||1888,year);s.continuity.lastAnnualYear=year;game.version='0.22.6';return {family:game.meta?.headless?null:familyState(game),disaster:s.disasters.event,globalDisaster,tactics:game.meta?.headless?null:tacticalContext(game,game.teamManagement?.tactics||{},game.teamManagement?.positions||[])}}
  function resolveDecision(game,decision,option){if(decision.type==='succession')return resolveSuccession(game,decision,option);if(decision.type==='major-disaster')return resolveDisaster(game,decision,option);return {ok:false,message:'This legacy decision is not supported.'}}
  function familyState(game){
    const s=ensure(game),year=yearOf(game.date);
    const people=s.family.people.map(p=>{
      const canonical=window.FLPeople?FLPeople.get(game,p.personId||p.id):null,row=canonical?{...p,...canonical}:p,age=year-Number(row.birthYear||year);
      return {...row,age,name:window.FLPeople?FLPeople.displayName(row):personName(p),portrait:window.FLEraIdentity?FLEraIdentity.portraitFor({...row,age},year):'assets/player-faces/no-face.svg'};
    });
    const current=people.find(p=>p.id===s.family.currentManagerPersonId||p.personId===s.family.currentManagerPersonId)||null;
    return {people,links:s.family.links,currentManager:current,successions:s.family.successionHistory,playerDynasties:s.family.playerDynasties,eligibleSuccessors:eligibleSuccessors(game)};
  }
  function disasterState(game){return ensure(game).disasters}
  function continuityState(game){const s=ensure(game);return {...s.continuity,activeFutureMarkets:activeFutureMarkets(game),safeThrough2150:Number(s.continuity.validatedThrough)>=2150}}

  return {ensure,normaliseFace,mutateFace,avatarSvg,managerPortrait,familyState,disasterState,continuityState,tacticalContext,recordTacticalUse,activeFutureMarkets,processDate,annualUpdate,resolveDecision,generateFamilyThrough,triggerDisaster,_careerTools:{queueSuccession,appointPerson,eligibleSuccessors}};
})();
