window.FLPlayerCareer = (() => {
  const VERSION='0.30.0-player-career-foundation',KEY='footballLegacyPlayerCareerV1';
  const TIERS={
    grassroots:{label:'Saturday/Sunday Grassroots',short:'Grassroots',level:0,difficulty:36},
    school:{label:'School & District Representative',short:'District XI',level:1,difficulty:42},
    trial:{label:'Academy Trial',short:'Trial',level:2,difficulty:48},
    'academy-u14':{label:'Youth Academy U14',short:'U14',level:3,difficulty:50},
    'academy-u16':{label:'Youth Academy U16',short:'U16',level:4,difficulty:56},
    'academy-u18':{label:'Youth Academy U18',short:'U18',level:5,difficulty:62},
    reserves:{label:'Reserves / U21',short:'Reserves',level:6,difficulty:68},
    cameo:{label:'First-team Cameo',short:'First-team Cameo',level:7,difficulty:75},
    'first-team':{label:'First Team',short:'First Team',level:8,difficulty:78},
    veteran:{label:'Veteran / Lower-league First Team',short:'Veteran',level:7,difficulty:67}
  };
  const POSITION_WEIGHTS={GK:{goal:.001,assist:.015,clean:.34},FB:{goal:.025,assist:.11,clean:.08},HB:{goal:.06,assist:.14,clean:.04},W:{goal:.2,assist:.22,clean:0},IF:{goal:.24,assist:.2,clean:0},CF:{goal:.34,assist:.12,clean:0}};
  const OPPONENTS={
    grassroots:['The Railway Arms','Oakfield Social','The Crown & Anchor','Riverside Athletic','Kingsmead Sunday','Old Foundry FC','Park View Rovers','Red Lion Athletic'],
    youth:['North County Academy','City Development XI','Riverside Scholars','Metropolitan Youth','Coastal Academy','Vale Juniors','United Development','County Select'],
    reserve:['County Reserves','Athletic U21','City B','United Reserves','Rovers Development','Albion U21','Town Reserves','Academy Select'],
    senior:['Arsenal','Aston Villa','Chelsea','Everton','Liverpool','Manchester City','Manchester United','Newcastle United'],
    international:['Belgium','Croatia','Denmark','France','Germany','Italy','Netherlands','Portugal','Spain','Sweden','United States','Brazil','Argentina','Japan','Morocco','Nigeria']
  };
  const FIRST=['Alex','Ben','Callum','Charlie','Daniel','Elliot','Finley','George','Harvey','Isaac','Jack','James','Joe','Leo','Lewis','Liam','Mason','Max','Noah','Oliver','Owen','Ryan','Sam','Theo','Tom','Will'];
  const LAST=['Adams','Baker','Bell','Brooks','Carter','Clarke','Collins','Cooper','Davies','Dawson','Edwards','Evans','Fisher','Foster','Gray','Green','Hall','Harris','Hill','Hughes','Jackson','Johnson','Jones','Kelly','King','Lee','Lewis','Martin','Miller','Mitchell','Morgan','Morris','Murphy','Parker','Price','Reed','Roberts','Robinson','Scott','Smith','Taylor','Thomas','Turner','Walker','Ward','White','Williams','Wilson','Wood','Wright'];
  const NATIONAL_TEAM={English:'England',Scottish:'Scotland',Welsh:'Wales','Northern Irish':'Northern Ireland',Irish:'Republic of Ireland',French:'France',German:'Germany',Spanish:'Spain',Italian:'Italy',Portuguese:'Portugal',Dutch:'Netherlands',Belgian:'Belgium',Danish:'Denmark',Swedish:'Sweden',Norwegian:'Norway',Polish:'Poland',Croatian:'Croatia',Serbian:'Serbia',Turkish:'Turkey',Brazilian:'Brazil',Argentine:'Argentina',Argentinian:'Argentina',Uruguayan:'Uruguay',American:'United States',Canadian:'Canada',Mexican:'Mexico',Japanese:'Japan',Korean:'South Korea',Nigerian:'Nigeria',Ghanaian:'Ghana',Senegalese:'Senegal',Moroccan:'Morocco',Egyptian:'Egypt',Australian:'Australia',Colombian:'Colombia'};
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
  const iso=date=>new Date(date).toISOString().slice(0,10);
  const addDays=(date,days)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return iso(d)};
  const hash=text=>{let h=2166136261;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
  function rand(c){c.rngState=(Math.imul(c.rngState||1,1664525)+1013904223)>>>0;return c.rngState/4294967296}
  const pick=(c,rows)=>rows[Math.floor(rand(c)*rows.length)];
  const playerName=c=>`${c.player.firstName} ${c.player.lastName}`;
  const tier=c=>TIERS[c.path.tier]||TIERS.grassroots;
  const currentStint=c=>c.records.stints[c.records.stints.length-1];
  const totals=()=>({appearances:0,starts:0,minutes:0,goals:0,assists:0,cleanSheets:0,yellowCards:0,redCards:0,playerOfMatch:0,ratingTotal:0});

  function attributes(position,archetype,seed){
    const r=(()=>{let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296}})(),base={pace:48,shooting:45,passing:47,dribbling:46,defending:44,physical:45,goalkeeping:22,stamina:50,technique:47,vision:45,leadership:40};
    const boosts={GK:{goalkeeping:31,defending:8,shooting:-18,pace:-8},FB:{pace:8,defending:9,stamina:9},HB:{passing:7,defending:8,vision:6,stamina:5},W:{pace:13,dribbling:11,shooting:5,defending:-8},IF:{passing:10,dribbling:9,vision:10,shooting:5},CF:{shooting:14,physical:7,pace:5,defending:-10}}[position]||{};
    Object.entries(boosts).forEach(([k,v])=>base[k]+=v);if(/Playmaker|Creator|Ten/.test(archetype)){base.passing+=5;base.vision+=7}if(/Finisher|Forward/.test(archetype))base.shooting+=5;if(/Defensive|Ball-winning/.test(archetype))base.defending+=5;if(/Explosive|Overlapping/.test(archetype))base.pace+=5;
    Object.keys(base).forEach(k=>base[k]=clamp(Math.round(base[k]+(r()-.5)*8),20,72));return base;
  }
  function overallFrom(c){const a=c.player.attributes,p=c.player.position,keys=p==='GK'?['goalkeeping','defending','physical','passing']:p==='FB'?['pace','defending','stamina','passing']:p==='HB'?['passing','defending','vision','stamina']:p==='W'?['pace','dribbling','passing','shooting']:p==='IF'?['passing','dribbling','vision','shooting']:['shooting','physical','pace','technique'];return Math.round(keys.reduce((n,k)=>n+a[k],0)/keys.length)}
  function addHistory(c,type,title,text,extra={}){const row={id:`pc-history-${c.history.length+1}-${c.date}`,date:c.date,season:c.season,type,title,text,...extra};c.history.unshift(row);if(c.history.length>1200)c.history=c.history.slice(0,1200);return row}
  function inbox(c,from,subject,body,type='general'){const row={id:`pc-inbox-${c.inbox.length+1}-${c.date}`,date:c.date,from,subject,body,type,read:false};c.inbox.unshift(row);if(c.inbox.length>300)c.inbox=c.inbox.slice(0,300);return row}
  function makeSquad(c){const positions=['GK','GK','FB','FB','FB','HB','HB','HB','W','W','IF','IF','CF','CF','CF','FB','HB','W','IF','CF'];return positions.map((position,index)=>{const age=Math.max(14,c.player.age-1+Math.floor(rand(c)*5)),ability=clamp(c.player.overall-8+Math.round(rand(c)*20),35,88);return{id:`mate-${c.season}-${index}-${Math.floor(rand(c)*99999)}`,name:`${pick(c,FIRST)} ${pick(c,LAST)}`,position,age,ability,form:'—',relationship:45+Math.floor(rand(c)*26),role:index<11?'Starter':index<16?'Rotation':'Prospect'}})}
  function startingClub(config){if(config.entry==='academy'&&config.club)return{id:config.club.id,name:config.club.name,league:config.club.league||'Academy football',tier:Number(config.club.tier)||1,strength:Number(config.club.currentStrength)||58,prestige:Number(config.club.prestige)||55,location:config.club.location||'England'};return{id:'pc-riverside-juniors',name:'Riverside Juniors',league:'Local Saturday & Sunday League',tier:15,strength:32,prestige:18,location:'England'}}
  function create(config){
    const seed=hash(`${config.firstName}-${config.lastName}-${config.nationality}-${Date.now()}`),club=startingClub(config),startTier=config.entry==='academy'?'academy-u14':'grassroots',attrs=attributes(config.position,config.archetype,seed);
    const c={version:VERSION,mode:'player-career',createdAt:new Date().toISOString(),lastSaved:null,rngState:seed,date:'2026-08-01',season:2026,seasonWeek:0,seasonMatches:0,retired:false,retirementPath:null,ui:{view:'home',notice:'',selectedInbox:null},player:{id:`pc-player-${seed}`,firstName:config.firstName,lastName:config.lastName,name:`${config.firstName} ${config.lastName}`,age:14,birthYear:2012,nationality:config.nationality,nationalTeam:NATIONAL_TEAM[config.nationality]||config.nationality.replace(/ian$/,'y'),position:config.position,foot:config.foot,height:config.height,archetype:config.archetype,attributes:attrs,overall:0,potential:clamp(78+Math.floor((seed%19)),80,96),traits:[],fitness:100,fatigue:0,morale:66,form:6.5,leadership:attrs.leadership,reputation:3,fans:120,clubCaptain:false,squadNumber:null},club,path:{entry:config.entry,tier:startTier,previousTier:null,coachTrust:config.entry==='academy'?52:35,scoutingAttention:config.entry==='grassroots'?8:0,stinkers:0,cameoMatchesRemaining:0,trialMatchesRemaining:0,releaseCount:0,promotionCount:0,redemptionCount:0,lastMovement:null},relationships:{manager:52,teammates:50,fans:48,agent:55,family:72,nationalManager:35,nationalTeammates:40},contract:{status:config.entry==='academy'?'Academy registration':'Amateur',role:'Prospect',weeklyWage:0,yearsRemaining:config.entry==='academy'?2:0,expires:'2028-06-30'},agent:{name:'Maya Bennett',reputation:35,transferInterest:[],endorsements:[],lastMeeting:null},international:{team:NATIONAL_TEAM[config.nationality]||config.nationality.replace(/ian$/,'y'),level:'Not selected',calledUp:false,caps:0,starts:0,goals:0,assists:0,captaincies:0,youthCaps:0,youthGoals:0,lastCallup:null,nextMatch:null},training:{usedThisWeek:false,lastFocus:null,streak:0,skillPoints:0},outside:{money:0,socialFollowers:80,publicImage:50,familyTime:50,lifestyle:'Grounded',actionUsedThisWeek:false},records:{totals:totals(),season:totals(),matches:[],internationalMatches:[],seasons:[],stints:[{id:`stint-${startTier}-2026`,from:'2026-08-01',to:'Present',clubId:club.id,club:club.name,tier:startTier,tierLabel:TIERS[startTier].label,appearances:0,goals:0,assists:0,averageRating:0,ratingTotal:0}],clubs:[club]},history:[],inbox:[],objectives:[],squad:[]};
    c.social={teammateActionUsed:false};c.player.overall=overallFrom(c);c.squad=makeSquad(c);setObjectives(c);addHistory(c,'career-start','The journey begins',`${playerName(c)} begins an open-ended playing career at age 14 with ${club.name} in ${tier(c).label}.`,{milestone:true});inbox(c,config.entry==='academy'?'Academy Director':'Riverside Juniors',`Welcome, ${config.firstName}`,config.entry==='academy'?`You are registered with our U14 group. Development matters more than hype: train well, earn the coach's trust and take each promotion when it comes.`:`Local football is where your story starts. Play well enough and school selectors and academy scouts will begin to notice.`,'welcome');return c;
  }
  function setObjectives(c){const t=tier(c),position=c.player.position;c.objectives=[{id:'rating',label:'Average match rating',target:t.level<3?6.7:6.8,value:0,unit:''},{id:'trust',label:'Coach trust',target:Math.min(85,55+t.level*4),value:Math.round(c.path.coachTrust),unit:'/100'},{id:'output',label:position==='GK'?'Clean sheets':'Goals + assists',target:t.level<5?8:12,value:0,unit:''}]}
  function nextFixture(c){
    if(c.retired)return null;const internationalDue=c.international.calledUp&&c.seasonWeek>0&&c.seasonWeek%9===0;
    if(internationalDue){let opponent=pick(c,OPPONENTS.international.filter(n=>n!==c.international.team)),senior=c.international.level==='Senior squad';return{date:addDays(c.date,7),opponent,competition:senior?'International fixture':'Youth international',international:true,venue:rand(c)<.5?'Home':'Away',keyMoment:senior?c.international.caps===0:c.international.youthCaps===0}}
    const group=c.path.tier==='grassroots'||c.path.tier==='school'?'grassroots':c.path.tier.startsWith('academy')||c.path.tier==='trial'?'youth':c.path.tier==='reserves'?'reserve':'senior',opponent=pick(c,OPPONENTS[group]);
    const keyMoment=['cameo','trial'].includes(c.path.tier)||c.records.totals.appearances===0||c.records.totals.appearances===49||c.records.totals.appearances===99;
    return{date:addDays(c.date,7),opponent,competition:tier(c).label,international:false,venue:rand(c)<.52?'Home':'Away',keyMoment};
  }
  function ratingFor(c,fixture){
    const t=fixture.international?{difficulty:78,level:9}:tier(c),quality=(c.player.overall-t.difficulty)/14,fitness=(c.player.fitness-70)/35,morale=(c.player.morale-50)/50,training=c.training.usedThisWeek?.18:0,noise=(rand(c)+rand(c)+rand(c)-1.5)*1.35;
    return clamp(6.25+quality*.48+fitness*.32+morale*.35+training+noise,4.1,9.8)
  }
  function minutesFor(c,fixture){if(fixture.international)return c.international.caps===0?20+Math.floor(rand(c)*35):c.relationships.nationalManager>=65?70+Math.floor(rand(c)*21):25+Math.floor(rand(c)*55);if(c.path.tier==='cameo')return 12+Math.floor(rand(c)*50);if(c.path.coachTrust<28)return 15+Math.floor(rand(c)*35);if(c.path.coachTrust<50)return 45+Math.floor(rand(c)*35);return 70+Math.floor(rand(c)*21)}
  function updateStats(target,match){target.appearances++;if(match.started)target.starts++;target.minutes+=match.minutes;target.goals+=match.goals;target.assists+=match.assists;target.cleanSheets+=match.cleanSheet?1:0;target.yellowCards+=match.yellowCards;target.redCards+=match.redCards;target.playerOfMatch+=match.playerOfMatch?1:0;target.ratingTotal+=match.rating}
  function average(target){return target.appearances?+(target.ratingTotal/target.appearances).toFixed(2):0}
  function outputValue(c){return c.player.position==='GK'?c.records.season.cleanSheets:c.records.season.goals+c.records.season.assists}
  function refreshObjectives(c){const by=Object.fromEntries(c.objectives.map(o=>[o.id,o]));if(by.rating)by.rating.value=average(c.records.season);if(by.trust)by.trust.value=Math.round(c.path.coachTrust);if(by.output)by.output.value=outputValue(c)}
  function recordMatch(c,match){c.records.matches.unshift(match);if(c.records.matches.length>1800)c.records.matches=c.records.matches.slice(0,1800);if(match.international){c.records.internationalMatches.unshift(match);return}updateStats(c.records.totals,match);updateStats(c.records.season,match);const stint=currentStint(c);stint.appearances++;stint.goals+=match.goals;stint.assists+=match.assists;stint.ratingTotal+=match.rating;stint.averageRating=+(stint.ratingTotal/stint.appearances).toFixed(2)}
  function maybeCard(c,rating){const aggression=(100-c.player.attributes.leadership)/130;return rand(c)<.035+aggression*.04?rand(c)<.08?{yellow:0,red:1}:{yellow:1,red:0}:{yellow:0,red:0}}
  function simulateMatch(c){
    const fixture=nextFixture(c);if(!fixture)return{ok:false,message:'This playing career has ended.'};c.date=fixture.date;c.seasonWeek++;const minutes=minutesFor(c,fixture),rating=ratingFor(c,fixture),weights=POSITION_WEIGHTS[c.player.position]||POSITION_WEIGHTS.CF,share=minutes/90,goals=rand(c)<weights.goal*share*clamp((rating-4.5)/2.8,.15,1.7)?1+(rating>9&&rand(c)<.22?1:0):0,assists=rand(c)<weights.assist*share*clamp((rating-4.8)/2.5,.18,1.6)?1:0,cleanSheet=c.player.position==='GK'&&rand(c)<weights.clean*clamp((rating-4.8)/2.5,.15,1.7),cards=maybeCard(c,rating),teamGoals=clamp(Math.floor(rand(c)*3)+goals,0,6),oppGoals=cleanSheet?0:clamp(Math.floor(rand(c)*3),0,5),started=minutes>=60,playerOfMatch=rating>=8.5&&rating>=6.8+rand(c)*1.8,captain=fixture.international?internationalCaptain(c):clubCaptain(c),match={id:`pc-match-${c.records.matches.length+1}-${c.date}`,date:c.date,season:c.season,club:fixture.international?c.international.team:c.club.name,tier:c.path.tier,tierLabel:fixture.competition,opponent:fixture.opponent,competition:fixture.competition,venue:fixture.venue,international:fixture.international,minutes,started,rating:+rating.toFixed(2),goals,assists,cleanSheet,yellowCards:cards.yellow,redCards:cards.red,playerOfMatch,captain,result:`${teamGoals}-${oppGoals}`,won:teamGoals>oppGoals,drawn:teamGoals===oppGoals,keyMoment:fixture.keyMoment};
    recordMatch(c,match);c.player.fitness=clamp(c.player.fitness-8-minutes/15-c.player.fatigue*.08,20,100);c.player.fatigue=clamp(c.player.fatigue+minutes/10,0,100);c.player.form=+(c.player.form*.68+rating*.32).toFixed(2);c.player.morale=clamp(c.player.morale+(rating-6.4)*3+(match.won?1:-1),10,100);c.player.fans=Math.max(0,Math.round(c.player.fans+(rating-6.1)*18+goals*28+assists*16+(playerOfMatch?45:0)));c.player.reputation=clamp(c.player.reputation+(rating-6.3)*.34+(fixture.international?.8:0)+(fixture.keyMoment&&rating>=8?.8:0),0,100);c.outside.socialFollowers=Math.max(0,Math.round(c.outside.socialFollowers+(rating-5.8)*12+goals*30+(fixture.international?35:0)));
    if(fixture.international)processInternationalMatch(c,match);else processClubMatch(c,match);c.relationships.fans=clamp(c.relationships.fans+(rating-6.2)*2.3+goals*2,0,100);c.relationships.teammates=clamp(c.relationships.teammates+(assists?2:0)+(rating>=7.5?1:rating<5.5?-2:0),0,100);c.training.usedThisWeek=false;c.outside.actionUsedThisWeek=false;c.social.teammateActionUsed=false;recover(c);refreshObjectives(c);maybeInterest(c,match);maybeInternational(c);maybeMovement(c,match);if(c.seasonWeek>=40)closeSeason(c);save(c);return{ok:true,match,message:matchSummary(c,match)}
  }
  function matchSummary(c,m){const pieces=[`${m.club} ${m.result} ${m.opponent}`,`${m.minutes} minutes · ${m.rating.toFixed(2)} rating`];if(m.goals)pieces.push(`${m.goals} goal${m.goals===1?'':'s'}`);if(m.assists)pieces.push(`${m.assists} assist${m.assists===1?'':'s'}`);if(m.captain)pieces.push('captain');return pieces.join(' · ')}
  function processClubMatch(c,m){const delta=(m.rating-6.45)*4+(m.goals*1.5)+(m.assists*.8)+(m.playerOfMatch?3:0)-(m.redCards?8:0);c.path.coachTrust=clamp(c.path.coachTrust+delta,0,100);c.relationships.manager=clamp(c.relationships.manager+delta*.45,0,100);if(m.rating<5.7&&m.minutes>=45)c.path.stinkers++;else if(m.rating>=6.45)c.path.stinkers=Math.max(0,c.path.stinkers-1);if(['grassroots','school','trial'].includes(c.path.tier))c.path.scoutingAttention=clamp(c.path.scoutingAttention+Math.max(-2,(m.rating-6.15)*5+m.goals*3+m.assists*2),0,100);if(m.playerOfMatch)inbox(c,'Local Football Desk','Player of the match',`${playerName(c)} was named player of the match after a ${m.rating.toFixed(2)} performance against ${m.opponent}.`,'media')}
  function processInternationalMatch(c,m){
    const senior=c.international.level==='Senior squad';
    if(senior){c.international.caps++;if(m.started)c.international.starts++;c.international.goals+=m.goals;c.international.assists+=m.assists;if(m.captain)c.international.captaincies++}
    else{c.international.youthCaps++;c.international.youthGoals+=m.goals}
    c.relationships.nationalManager=clamp(c.relationships.nationalManager+(m.rating-6.4)*3,0,100);c.relationships.nationalTeammates=clamp(c.relationships.nationalTeammates+(m.rating-6.2)*2+(m.assists?2:0),0,100);
    const title=senior?(m.captain?'International captaincy':c.international.caps===1?'Senior international debut':'International appearance'):(c.international.youthCaps===1?'Youth international debut':'Youth international appearance');
    addHistory(c,'international',title,`${playerName(c)} ${m.captain?'captains':'represents'} ${c.international.team} against ${m.opponent}, earning a ${m.rating.toFixed(2)} rating.`,{milestone:(senior?c.international.caps:c.international.youthCaps)===1||m.captain,matchId:m.id})
  }
  function internationalCaptain(c){if(c.international.level!=='Senior squad')return false;const eligible=c.player.age>=24&&c.international.caps>=20&&c.player.attributes.leadership>=72&&c.relationships.nationalManager>=62;return eligible&&(c.international.captaincies>0||rand(c)<.18)}
  function clubCaptain(c){const eligible=['first-team','veteran'].includes(c.path.tier)&&c.player.age>=23&&c.player.attributes.leadership>=72&&c.path.coachTrust>=78&&c.relationships.teammates>=65;c.player.clubCaptain=eligible&&(c.player.clubCaptain||rand(c)<.12);return c.player.clubCaptain}
  function moveTier(c,newTier,reason,options={}){if(!TIERS[newTier]||newTier===c.path.tier)return;const old=c.path.tier,stint=currentStint(c);stint.to=c.date;c.path.previousTier=old;c.path.tier=newTier;c.path.lastMovement={date:c.date,from:old,to:newTier,reason};c.path.stinkers=0;c.path.coachTrust=options.trust??clamp(c.path.coachTrust,28,78);c.path.promotionCount+=TIERS[newTier].level>TIERS[old].level?1:0;c.path.releaseCount+=options.release?1:0;if(options.redemption)c.path.redemptionCount++;c.records.stints.push({id:`stint-${newTier}-${c.date}-${c.records.stints.length}`,from:c.date,to:'Present',clubId:c.club.id,club:c.club.name,tier:newTier,tierLabel:TIERS[newTier].label,appearances:0,goals:0,assists:0,averageRating:0,ratingTotal:0});addHistory(c,options.release?'release':TIERS[newTier].level>TIERS[old].level?'promotion':'demotion',options.title||`${TIERS[newTier].label}`,reason,{milestone:true,fromTier:old,toTier:newTier});inbox(c,options.from||'Football Department',options.title||`New playing level: ${TIERS[newTier].short}`,reason,options.release?'release':'career');setObjectives(c)}
  function maybeMovement(c,m){
    const id=c.path.tier,age=c.player.age,trust=c.path.coachTrust,attention=c.path.scoutingAttention;
    if(id==='grassroots'&&attention>=42){moveTier(c,'school',`A run of strong local performances earns ${playerName(c)} selection for the district representative side.`,{trust:48,title:'District call-up',redemption:c.path.releaseCount>0,from:'District Schools FA'});return}
    if(id==='school'&&attention>=70){moveTier(c,'trial',`${c.club.name} invite ${playerName(c)} to a three-match academy trial after sustained scouting interest.`,{trust:50,title:'Academy trial offered',redemption:c.path.releaseCount>0,from:'Academy Recruitment'});c.path.trialMatchesRemaining=3;return}
    if(id==='trial'){c.path.trialMatchesRemaining--;if(c.path.trialMatchesRemaining<=0){if(average(currentStint(c))>=6.45||trust>=58)moveTier(c,age<=14?'academy-u14':age<=16?'academy-u16':'academy-u18',`${playerName(c)} earns an academy registration after completing the trial.`,{trust:52,title:'Academy place earned',redemption:true,from:'Academy Director'});else moveTier(c,'grassroots',`The academy decide not to offer terms after the trial. ${playerName(c)} returns to local football with the scouting trail still alive.`,{trust:38,title:'Trial ends without an offer',release:true,from:'Academy Director'})}return}
    if(['academy-u14','academy-u16','academy-u18'].includes(id)&&c.path.stinkers>=3&&trust<22){moveTier(c,'grassroots',`Three damaging performances and falling coach trust lead ${c.club.name} to release ${playerName(c)}. The career continues back in local football.`,{trust:34,title:'Released by the academy',release:true,from:'Academy Director'});c.path.scoutingAttention=12;return}
    if(id==='academy-u14'&&(age>=15||trust>=78)){moveTier(c,'academy-u16',`${playerName(c)} is moved up to the U16 group after earning the staff's confidence.`,{trust:54,title:'Promoted to U16s',from:'Academy Director'});return}
    if(id==='academy-u16'&&(age>=17||trust>=80)){moveTier(c,'academy-u18',`${playerName(c)} steps into U18 football, with training intensity and selection pressure increasing.`,{trust:55,title:'Promoted to U18s',from:'Academy Director'});return}
    if(id==='academy-u18'&&age>=17&&trust>=72&&c.player.overall>=58){moveTier(c,'reserves',`${playerName(c)} earns a place with the reserves and U21 group. First-team football is now within sight.`,{trust:56,title:'Promoted to the reserves',from:'Head of Development'});return}
    if(id==='reserves'&&trust>=78&&c.player.overall>=64&&rand(c)<.22){moveTier(c,'cameo',`An injury shortage creates a rare first-team opportunity. ${playerName(c)} is included for one senior match before returning to the development group.`,{trust:58,title:'First-team cameo',from:'First-team Manager'});c.path.cameoMatchesRemaining=1;return}
    if(id==='cameo'){c.path.cameoMatchesRemaining--;if(m.rating>=8.3){moveTier(c,'first-team',`An exceptional ${m.rating.toFixed(2)} cameo changes the plan. ${playerName(c)} is retained with the senior squad.`,{trust:65,title:'Fast-tracked to the first team',from:'First-team Manager'});c.contract={status:'Professional',role:'Breakthrough Prospect',weeklyWage:250+Math.round(c.club.prestige*8),yearsRemaining:3,expires:`${c.season+3}-06-30`}}else moveTier(c,'reserves',`${playerName(c)} returns to the reserves after the planned first-team cameo. The experience remains a major career milestone.`,{trust:62,title:'Cameo complete',from:'Head of Development'});return}
    if(id==='reserves'&&trust>=86&&c.player.overall>=68){moveTier(c,'first-team',`${playerName(c)} is promoted permanently after sustained reserve form and strong coach trust.`,{trust:66,title:'Senior promotion',from:'First-team Manager'});c.contract={status:'Professional',role:'Squad Player',weeklyWage:400+Math.round(c.club.prestige*11),yearsRemaining:3,expires:`${c.season+3}-06-30`};return}
    if(id==='first-team'&&c.path.stinkers>=4&&trust<20){moveTier(c,'reserves',`A damaging run costs ${playerName(c)} a first-team place. The manager sends the player back to the reserves to rebuild.`,{trust:38,title:'Dropped from the first team',from:'First-team Manager'});return}
    if(id==='first-team'&&age>=34&&c.player.overall<68){moveTier(c,'veteran',`${playerName(c)} accepts a veteran role as physical decline changes the shape of the career.`,{trust:60,title:'Veteran chapter begins',from:'Agent'});return}
    if(id==='veteran'&&age>=38&&c.player.overall<53&&trust<32){moveTier(c,'grassroots',`${playerName(c)} is not offered another senior contract and chooses to keep playing in local football instead of retiring.`,{trust:48,title:'Back where it began',release:true,from:'Agent'});c.path.scoutingAttention=30}
  }
  function maybeInternational(c){const p=c.player,i=c.international,seniorEligible=p.age>=17&&(['first-team','cameo','veteran'].includes(c.path.tier)||p.overall>=72)&&p.reputation>=22;if(seniorEligible&&i.level!=='Senior squad'){i.level='Senior squad';i.calledUp=true;i.lastCallup=c.date;i.nextMatch=addDays(c.date,21);c.relationships.nationalManager=50;inbox(c,`${i.team} National Team`,'Senior international call-up',`${playerName(c)} has been selected for the senior ${i.team} squad. Places and captaincy must now be earned through performances.`,'international');addHistory(c,'international','Senior call-up',`${playerName(c)} receives a first senior call-up for ${i.team}.`,{milestone:true});return}if(!seniorEligible&&p.age>=16&&p.age<=21&&p.overall>=57&&i.level==='Not selected'){i.level=p.age<=17?'Under-17 squad':'Under-21 squad';i.calledUp=true;i.lastCallup=c.date;i.nextMatch=addDays(c.date,21);inbox(c,`${i.team} Youth Football`,`${i.level} call-up`,`${playerName(c)} has been selected for the next youth international camp.`,'international');addHistory(c,'international','Youth international call-up',`${playerName(c)} enters the ${i.team} youth setup.`,{milestone:true})}}
  function maybeInterest(c,m){if(m.international||c.records.totals.appearances%8!==0||!['reserves','first-team','veteran'].includes(c.path.tier))return;if(m.rating>=7.1&&rand(c)<.45){const level=clamp(c.club.tier+(rand(c)<.45?-1:rand(c)<.5?0:1),1,6),names=['Arsenal','Aston Villa','Chelsea','Everton','Liverpool','Manchester City','Manchester United'],club=pick(c,names),league={1:'Premier League',2:'EFL Championship',3:'EFL League One',4:'EFL League Two',5:'National League',6:'National League North / South'}[level],offer={id:`offer-${c.date}-${c.agent.transferInterest.length}`,club,league,tier:level,role:level<c.club.tier?'Rotation':level===c.club.tier?'First Team':'Key Player',weeklyWage:Math.max(50,Math.round((c.player.overall*14+c.player.reputation*22)*(7-level)/4)),years:2+Math.floor(rand(c)*3),expires:addDays(c.date,28),status:'open'};c.agent.transferInterest.unshift(offer);inbox(c,c.agent.name,`Interest from ${club}`,`${club} have contacted me. They see you as a ${offer.role.toLowerCase()} and are prepared to discuss a ${offer.years}-year contract.`,'agent')}}
  function acceptOffer(c,id){const offer=c.agent.transferInterest.find(o=>o.id===id&&o.status==='open');if(!offer)return{ok:false,message:'That offer is no longer available.'};const old=c.club,stint=currentStint(c);stint.to=c.date;c.club={id:`pc-club-${hash(offer.club)}`,name:offer.club,league:offer.league,tier:offer.tier,strength:clamp(82-offer.tier*5,45,80),prestige:clamp(85-offer.tier*7,35,82),location:'England'};if(!c.records.clubs.some(x=>x.id===c.club.id))c.records.clubs.push(c.club);c.path.coachTrust=offer.role==='Key Player'?72:offer.role==='First Team'?62:50;c.contract={status:'Professional',role:offer.role,weeklyWage:offer.weeklyWage,yearsRemaining:offer.years,expires:`${c.season+offer.years}-06-30`};c.records.stints.push({id:`stint-transfer-${c.date}`,from:c.date,to:'Present',clubId:c.club.id,club:c.club.name,tier:c.path.tier,tierLabel:tier(c).label,appearances:0,goals:0,assists:0,averageRating:0,ratingTotal:0});offer.status='accepted';c.agent.transferInterest.filter(x=>x.id!==id&&x.status==='open').forEach(x=>x.status='closed');c.squad=makeSquad(c);addHistory(c,'transfer',`${c.club.name} sign ${playerName(c)}`,`${playerName(c)} leaves ${old.name} for ${c.club.name}, accepting a ${offer.years}-year contract as a ${offer.role.toLowerCase()}.`,{milestone:true,fromClub:old.name,toClub:c.club.name});inbox(c,c.agent.name,'Transfer completed',`The move to ${c.club.name} is complete. Your new role is ${offer.role} on £${offer.weeklyWage.toLocaleString('en-GB')} per week.`,'agent');save(c);return{ok:true,message:`Transfer to ${c.club.name} completed.`}}
  function train(c,focus){if(c.training.usedThisWeek)return{ok:false,message:'You have already completed personal training this week.'};const map={pace:['pace','stamina'],finishing:['shooting','technique'],passing:['passing','vision'],dribbling:['dribbling','technique'],defending:['defending','physical'],goalkeeping:['goalkeeping','vision'],leadership:['leadership','vision'],recovery:[]},keys=map[focus]||[];if(focus==='recovery'){c.player.fitness=clamp(c.player.fitness+20,0,100);c.player.fatigue=clamp(c.player.fatigue-20,0,100);c.player.morale=clamp(c.player.morale+2,0,100)}else{keys.forEach(k=>{const room=Math.max(0,c.player.potential-c.player.attributes[k]);if(room>0)c.player.attributes[k]=clamp(c.player.attributes[k]+(rand(c)<.34?1:0),20,99)});c.player.fatigue=clamp(c.player.fatigue+8,0,100);c.player.fitness=clamp(c.player.fitness-5,0,100);c.training.skillPoints+=1;c.path.coachTrust=clamp(c.path.coachTrust+1.2,0,100)}c.training.usedThisWeek=true;c.training.lastFocus=focus;c.training.streak++;c.player.overall=overallFrom(c);save(c);return{ok:true,message:focus==='recovery'?'Recovery completed. Fitness and fatigue improved.':`${focus[0].toUpperCase()+focus.slice(1)} session completed.`}}
  function lifestyle(c,choice){if(c.outside.actionUsedThisWeek)return{ok:false,message:'You have already made an outside-football choice this week.'};const actions={family:()=>{c.relationships.family+=6;c.player.morale+=3;c.outside.publicImage+=1},rest:()=>{c.player.fitness+=12;c.player.fatigue-=14;c.outside.socialFollowers-=2},extra:()=>{c.player.fatigue+=12;c.player.fitness-=6;c.path.coachTrust+=2;c.training.skillPoints+=2},social:()=>{c.outside.socialFollowers+=Math.round(30+c.player.reputation*3);c.relationships.fans+=3;c.outside.publicImage+=rand(c)<.18?-5:2},nightlife:()=>{c.player.morale+=6;c.player.fatigue+=16;c.player.fitness-=10;c.path.coachTrust-=rand(c)<.25?7:0;c.outside.publicImage-=rand(c)<.2?6:0}};if(!actions[choice])return{ok:false,message:'Unknown lifestyle choice.'};actions[choice]();['family','fans'].forEach(k=>c.relationships[k]=clamp(c.relationships[k],0,100));c.player.morale=clamp(c.player.morale,0,100);c.player.fitness=clamp(c.player.fitness,0,100);c.player.fatigue=clamp(c.player.fatigue,0,100);c.outside.publicImage=clamp(c.outside.publicImage,0,100);c.outside.actionUsedThisWeek=true;save(c);return{ok:true,message:'Choice recorded. Its effects will carry into the next match.'}}
  function managerTalk(c,choice){const actions={minutes:{need:55,good:'The manager agrees to give you a clearer opportunity.',bad:'The manager says your performances do not justify more minutes.'},role:{need:65,good:'Your expected squad role has been upgraded.',bad:'The manager refuses to change your role.'},feedback:{need:0,good:`The manager wants improved consistency and an average rating above ${c.objectives[0].target}.`,bad:''},support:{need:35,good:'The honest conversation improves trust on both sides.',bad:'The conversation becomes tense and trust falls.'}},a=actions[choice];if(!a)return{ok:false,message:'Conversation unavailable.'};const score=c.relationships.manager+c.path.coachTrust*.35+rand(c)*25,success=score>=a.need;c.relationships.manager=clamp(c.relationships.manager+(success?3:-4),0,100);if(choice==='minutes'&&success)c.path.coachTrust=clamp(c.path.coachTrust+3,0,100);if(choice==='role'&&success)c.contract.role=c.contract.role==='Prospect'?'Rotation':c.contract.role==='Rotation'?'First Team':c.contract.role;if(choice==='support')c.player.morale=clamp(c.player.morale+(success?4:-3),0,100);inbox(c,'Manager',`Conversation: ${choice}`,success?a.good:a.bad,'manager');save(c);return{ok:true,message:success?a.good:a.bad}}
  function teammateInteraction(c,id,choice='bond'){
    c.social=c.social||{teammateActionUsed:false};if(c.social.teammateActionUsed)return{ok:false,message:'You have already spent time with a teammate this week.'};const mate=c.squad.find(row=>row.id===id);if(!mate)return{ok:false,message:'That teammate is no longer in the squad.'};
    const rivalryWorks=rand(c)<.55,effects={bond:{personal:6,room:1,morale:2,text:`You spend time with ${mate.name} away from training and understand each other better.`},encourage:{personal:4,room:2,morale:1,text:`You encourage ${mate.name} before the next match and lift the dressing room.`},compete:{personal:rivalryWorks?3:-3,room:0,morale:1,text:`You challenge ${mate.name} in training. The rivalry ${rivalryWorks?'builds mutual respect':'creates some friction'}.`}},effect=effects[choice]||effects.bond;
    mate.relationship=clamp(mate.relationship+effect.personal,0,100);c.relationships.teammates=clamp(c.relationships.teammates+effect.room,0,100);c.player.morale=clamp(c.player.morale+effect.morale,0,100);c.social.teammateActionUsed=true;addHistory(c,'relationship',`Time with ${mate.name}`,effect.text,{teammateId:mate.id});save(c);return{ok:true,message:effect.text}
  }
  function recover(c){c.player.fitness=clamp(c.player.fitness+11,0,100);c.player.fatigue=clamp(c.player.fatigue-10,0,100)}
  function seasonDevelopment(c){const p=c.player,peak=p.position==='GK'?33:29,age=p.age,growth=age<=20?2.4:age<=24?1.35:age<=peak?.45:-(age-peak)*.52,mental=['passing','vision','leadership','technique'],physical=['pace','physical','stamina'];Object.keys(p.attributes).forEach(k=>{let change=growth+(rand(c)-.5)*1.3;if(age>peak&&mental.includes(k))change=Math.max(-.2,change+.55);if(age>peak&&physical.includes(k))change-=.7;if(p.attributes[k]>=p.potential)change=Math.min(0,change);p.attributes[k]=clamp(Math.round(p.attributes[k]+change),20,99)});p.overall=overallFrom(c)}
  function closeSeason(c){const record={season:`${c.season}-${String(c.season+1).slice(2)}`,age:c.player.age,club:c.club.name,tier:c.path.tier,tierLabel:tier(c).label,...c.records.season,averageRating:average(c.records.season),overall:c.player.overall,coachTrust:Math.round(c.path.coachTrust),internationalCaps:c.international.caps};c.records.seasons.unshift(record);addHistory(c,'season',`${record.season} season complete`,`${playerName(c)} records ${record.appearances} appearances, ${record.goals} goals, ${record.assists} assists and a ${record.averageRating.toFixed(2)} average rating for ${c.club.name}.`);c.season++;c.player.age++;c.seasonWeek=0;c.seasonMatches=0;c.records.season=totals();c.training.streak=0;c.contract.yearsRemaining=Math.max(0,c.contract.yearsRemaining-1);seasonDevelopment(c);if(c.contract.status==='Professional')c.outside.money+=c.contract.weeklyWage*40;if(c.contract.yearsRemaining===0&&c.contract.status==='Professional'){inbox(c,c.agent.name,'Contract decision approaching',`${c.club.name} have not automatically renewed your deal. Strong form will improve your options; you may also choose to drop a level or retire.`,'agent');c.contract.status='Expiring'}setObjectives(c);maybeInternational(c);addHistory(c,'birthday',`${c.player.age} years old`,`${playerName(c)} begins another season at age ${c.player.age} with an overall rating of ${c.player.overall}.`)}
  function quickSim(c,count=5){const results=[];for(let i=0;i<Math.max(1,Math.min(20,Number(count)||5))&&!c.retired;i++)results.push(simulateMatch(c));return results}
  function retire(c,path='leave'){if(c.retired)return{ok:false,message:'This career is already complete.'};c.retired=true;c.retirementPath=path;const stint=currentStint(c);if(stint)stint.to=c.date;addHistory(c,'retirement',`${playerName(c)} retires`,`${playerName(c)} retires at age ${c.player.age} after ${c.records.totals.appearances} recorded matches and ${c.international.caps} senior international caps.`,{milestone:true});save(c);return{ok:true,message:'Playing career complete. Your full legacy record has been preserved.'}}
  function managerIdentity(c){return{firstName:c.player.firstName,lastName:c.player.lastName,age:c.player.age,nationality:c.player.nationality,birthplace:c.club.location||'England',occupation:'Former Professional Footballer',managementStyle:'Balanced',style:'Balanced',temperament:c.player.attributes.leadership>=70?'Demanding':'Measured',reputation:c.player.reputation>=75?'International Player':c.international.caps?'Former International':'Former Footballer',playerCareerLegacy:{...c.records.totals,international:{...c.international},clubs:c.records.clubs,stints:c.records.stints}}}
  function save(c){if(!c)return false;c.lastSaved=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(c));return true}
  function load(){try{const c=JSON.parse(localStorage.getItem(KEY)||'null');return migrate(c)}catch(error){console.warn('Could not load Player Career.',error);return null}}
  function migrate(c){if(!c||c.mode!=='player-career')return c;if(window.FLOriginalNames?.restoreGame)FLOriginalNames.restoreGame(c);c.version=VERSION;c.ui=c.ui||{view:'home',notice:'',selectedInbox:null};c.history=Array.isArray(c.history)?c.history:[];c.inbox=Array.isArray(c.inbox)?c.inbox:[];c.relationships={manager:50,teammates:50,fans:50,agent:50,family:65,nationalManager:35,nationalTeammates:40,...c.relationships};c.social={teammateActionUsed:false,...c.social};c.international={team:c.player?.nationalTeam||NATIONAL_TEAM[c.player?.nationality]||c.player?.nationality||'England',level:'Not selected',calledUp:false,caps:0,starts:0,goals:0,assists:0,captaincies:0,youthCaps:0,youthGoals:0,lastCallup:null,nextMatch:null,...c.international};c.records=c.records||{};c.records.matches=Array.isArray(c.records.matches)?c.records.matches:[];c.records.internationalMatches=Array.isArray(c.records.internationalMatches)?c.records.internationalMatches:[];c.records.seasons=Array.isArray(c.records.seasons)?c.records.seasons:[];c.records.stints=Array.isArray(c.records.stints)?c.records.stints:[];c.records.clubs=Array.isArray(c.records.clubs)?c.records.clubs:[c.club].filter(Boolean);c.records.totals={...totals(),...c.records.totals};c.records.season={...totals(),...c.records.season};return c}
  function clear(){localStorage.removeItem(KEY)}
  return{VERSION,KEY,TIERS,create,save,load,clear,migrate,nextFixture,simulateMatch,quickSim,train,lifestyle,managerTalk,teammateInteraction,acceptOffer,retire,managerIdentity,average,overallFrom,tier};
})();
