'use strict';
const KEYS={players:'footballLegacyCreatedPlayersV1',stadiums:'footballLegacyCreatedStadiumsV1',clubs:'footballLegacyCreatedClubsV1'};
const CONFIG={players:{label:'Player',plural:'Players',create:'../create-player/index.html',createLabel:'Create New Player'},stadiums:{label:'Stadium',plural:'Stadiums',create:'../create-stadium/index.html',createLabel:'Create New Stadium'},clubs:{label:'Club',plural:'Clubs',create:'../create-club/index.html',createLabel:'Create New Club'}};
let activeTab='players';
function read(key){try{const rows=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(rows)?rows:[]}catch{return[]}}
function esc(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function number(value){return Number(value||0).toLocaleString('en-GB')}
function locationText(location={}){return [location.city||location.town,location.county,location.country].filter(Boolean).join(', ')||'Location not set'}
function teamName(id,clubs){if(!id||id==='free-agent')return'Free Agent';const club=clubs.find(row=>row.id===id);return club?.name||id.replaceAll('-',' ').replace(/\w/g,m=>m.toUpperCase())}
function swatches(colours={}){const values=[colours.primary,colours.secondary,colours.accent||colours.exterior].filter(Boolean);return values.length?`<div class="swatches">${values.map(value=>`<span class="swatch" style="background:${esc(value)}"></span>`).join('')}</div>`:''}
function playerCard(player,clubs){const name=`${player.firstName||''} ${player.lastName||''}`.trim()||'Unnamed Player';return`<article class="creation-card" style="--card-accent:${esc(player.kit?.primary||'#e87824')}"><span class="creation-type">Created Player</span><h2>${esc(name)}</h2><p class="creation-sub">${esc(player.primaryPosition||'Position unset')} · ${esc(player.nationality||'Nationality unset')} · Age ${esc(player.age||'—')}</p>${swatches(player.kit||{})}<div class="creation-meta"><div class="creation-row"><span>Overall</span><strong>${esc(player.overall||'—')}</strong></div><div class="creation-row"><span>Team</span><strong>${esc(teamName(player.teamId,clubs))}</strong></div><div class="creation-row"><span>Height</span><strong>${esc(player.appearance?.height||'—')} cm</strong></div></div><div class="creation-id">${esc(player.id)}</div><div class="creation-actions"><a class="action-button" href="../create-player/index.html">Open Player Creator</a></div></article>`}
function stadiumCard(stadium){return`<article class="creation-card" style="--card-accent:${esc(stadium.colours?.primary||'#e87824')}"><span class="creation-type">Created Stadium</span><h2>${esc(stadium.name||'Unnamed Stadium')}</h2><p class="creation-sub">${esc(locationText(stadium.location))}</p>${swatches(stadium.colours||{})}<div class="creation-meta"><div class="creation-row"><span>Capacity</span><strong>${number(stadium.capacity)}</strong></div><div class="creation-row"><span>Size</span><strong>${esc(stadium.size||'—')}</strong></div><div class="creation-row"><span>Pitch</span><strong>${esc((stadium.pitchWear||'—').replaceAll('-',' '))}</strong></div></div><div class="creation-id">${esc(stadium.id)}</div><div class="creation-actions"><a class="action-button" href="../create-stadium/index.html">Open Stadium Creator</a></div></article>`}
function clubCard(club,stadiums){const stadium=stadiums.find(row=>row.id===club.stadiumId);return`<article class="creation-card" style="--card-accent:${esc(club.colours?.primary||'#e87824')}"><span class="creation-type">Created Club</span><h2>${esc(club.name||'Unnamed Club')}</h2><p class="creation-sub">${esc(club.abbreviation||club.shortName||'Club')} · ${esc(locationText(club.location))}</p>${swatches(club.colours||{})}<div class="creation-meta"><div class="creation-row"><span>Overall</span><strong>${esc(club.ratings?.overall||'—')}</strong></div><div class="creation-row"><span>Squad</span><strong>${esc(club.squad?.playerIds?.length||0)} players</strong></div><div class="creation-row"><span>Stadium</span><strong>${esc(stadium?.name||club.stadiumId||'Automatic Ground')}</strong></div></div><div class="creation-id">${esc(club.id)}</div><div class="creation-actions"><a class="action-button" href="../create-club/index.html">Open Club Creator</a></div></article>`}
function counts(){const data={players:read(KEYS.players),stadiums:read(KEYS.stadiums),clubs:read(KEYS.clubs)};document.getElementById('playerTabCount').textContent=data.players.length;document.getElementById('stadiumTabCount').textContent=data.stadiums.length;document.getElementById('clubTabCount').textContent=data.clubs.length;return data}
function render(){const data=counts(),cfg=CONFIG[activeTab],grid=document.getElementById('creationGrid'),rows=data[activeTab];document.getElementById('libraryCount').innerHTML=`<strong>${rows.length}</strong> ${rows.length===1?cfg.label:cfg.plural} saved`;const link=document.getElementById('createNewLink');link.href=cfg.create;link.textContent=cfg.createLabel;const clubs=data.clubs,stadiums=data.stadiums;if(!rows.length){grid.innerHTML=`<div class="empty-library">No created ${cfg.plural.toLowerCase()} saved yet.<br><br><a class="action-button primary" href="${cfg.create}">${cfg.createLabel}</a></div>`;return}grid.innerHTML=rows.map(row=>activeTab==='players'?playerCard(row,clubs):activeTab==='stadiums'?stadiumCard(row):clubCard(row,stadiums)).join('')}
function setTab(tab){if(!CONFIG[tab])tab='players';activeTab=tab;document.querySelectorAll('[data-tab]').forEach(button=>button.classList.toggle('active',button.dataset.tab===tab));if(location.hash!==`#${tab}`)history.replaceState({},document.title,`#${tab}`);render()}
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>setTab(button.dataset.tab)));window.addEventListener('hashchange',()=>setTab(location.hash.slice(1)));setTab(location.hash.slice(1)||'players');
